---
HUB1:
    hostname: 12.12.12.10
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Hub
        ASN: 65001 

HUB2:
    hostname: 12.12.12.11
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Hub
        ASN: 65001 
   
S1:
    hostname: 12.12.12.2
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 

S2:
    hostname: 12.12.12.3
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 

S3:
    hostname: 12.12.12.4
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 

S4:
    hostname: 12.12.12.5
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 

S5:
    hostname: 12.12.12.6
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 

S6:
    hostname: 12.12.12.7
    groups:
        - IOS_group
    data: 
        domain: gh-lab.com
        dmvpn: Spoke
        ASN: 65001 