OSPF:
    rid: "11.11.11.5"
    loopback: "11.11.11.5/32"

BGP: 
    ASN: "65003"
    peers:
       - neighbor: "11.11.11.1"
         peer_asn: "65000"

       - neighbor: "11.11.11.2"
         peer_asn: "65000"
